server:
  port: 8080

spring:
  application:
    name: virtual-queue-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  threads:
    virtual:
      enabled: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: virtual-queue-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

queue:
  jwt:
    secret: ${QUEUE_JWT_SECRET:ticketstorm-queue-jwt-secret-key-that-is-long-enough-for-hs512-algorithm!}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
